# Generated by Django 5.1.1 on 2025-05-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_img_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
